### ISSUE TITLE
CreativeMode Using Xp to Level Up

### ISSUE THREAD

**Issue by Treehock** [dainxt/AncientClasses#11]
Version 1.18.2

Mod Version 1.0.4

Completely new world no other mods loaded

In creative mode to level up classes, you need levels first. This makes it a pain to test since you need to give yourself levels first before you can test the classes

Screenshots

No levels
![2022-04-01_16 46 13](https://user-images.githubusercontent.com/65260754/161339494-fc992a3e-676a-4e5d-a491-cd7b030e1822.png)

Cant level up
![2022-04-01_16 47 06](https://user-images.githubusercontent.com/65260754/161339496-35d07b17-c50f-43c0-8289-429cf7e7b352.png)

Add levels
![2022-04-01_16 47 49](https://user-images.githubusercontent.com/65260754/161339498-937ed024-1fa8-47f3-8973-6b86af76f60b.png)

Can level up
![2022-04-01_16 50 20](https://user-images.githubusercontent.com/65260754/161339502-71b81f34-311d-4691-940a-367dbee5134a.png)

**Comment by dainxt** [comment]
Added in 1.0.6
