### ISSUE TITLE
Plant Armour Duplication Creative Mode

### ISSUE THREAD

**Issue by Treehock** [dainxt/AncientClasses#12]
Version 1.18.2

Mod Version 1.0.4

Completely new world no other mods loaded

Plant armour will duplicate in creative mode. Not game-breaking but still an issue.

Screenshots

Amour's inventory
![2022-04-01_16 56 38](https://user-images.githubusercontent.com/65260754/161340332-dab7feda-fadb-4560-9f4e-24f4fea7ee74.png)

Player's inventory
![2022-04-01_16 56 44](https://user-images.githubusercontent.com/65260754/161340335-afabdece-ec8d-468a-9f35-52992b27680e.png)

After equiping
![2022-04-01_16 56 51](https://user-images.githubusercontent.com/65260754/161340336-796bb05c-a105-4ed8-9c23-a5e61df58370.png)

Second chestplate's inventory
![2022-04-01_16 57 02](https://user-images.githubusercontent.com/65260754/161340330-bbb05d83-b472-4d9f-b641-a03588c5f348.png)

**Comment by dainxt** [comment]
To be fair, this is the way the vanilla game handles equipable armor, but I find it kinda troublesome too on creative playtesting. Fixed in 1.0.6
