### ISSUE TITLE
Plant Armour Hotbar Placement Issue

### ISSUE THREAD

**Issue by Treehock** [dainxt/AncientClasses#13]
Version 1.18.2

Mod Version 1.0.4

Completely new world no other mods loaded

Tested in creative and survival 

You cant place items that cant go in the armour's inventory in your Hotbar when in the armour's GUI

Player's inventory
![2022-04-01_17 03 15](https://user-images.githubusercontent.com/65260754/161341199-87b293cd-0b0e-403a-a8bc-38a0dfbeabc6.png)

Item compatible with inventory (can place)
![2022-04-01_17 03 28](https://user-images.githubusercontent.com/65260754/161341204-e1d4f535-c164-46eb-a90d-ec3ef1bafe66.png)

Item incompatible with inventory (cant place)
![2022-04-01_17 03 44](https://user-images.githubusercontent.com/65260754/161341205-3875d9ad-d3f4-4a87-ae03-0839ef837e67.png)

**Comment by dainxt** [comment]
Fixed in 1.0.6
