### ISSUE TITLE
Ghastling Deletes Items

### ISSUE THREAD

**Issue by Treehock** [dainxt/AncientClasses#14]
Version 1.18.2

Mod Version 1.0.4

Completely new world no other mods loaded

When you place items in the Ghastling's inventory it deletes

Sceenshots

Summon Ghastling
![2022-04-01_17 15 56](https://user-images.githubusercontent.com/65260754/161342508-a77933cb-32c9-49c9-b473-0c4fd7640e6f.png)

Place items in inventory
![2022-04-01_17 16 10](https://user-images.githubusercontent.com/65260754/161342509-2ad3c851-53b3-41e1-b173-96444477d7e7.png)

Reopen Ghastlings inventory
![2022-04-01_17 16 15](https://user-images.githubusercontent.com/65260754/161342512-b695a8b3-d439-4d5b-9e68-7a5d81bfc012.png)

**Comment by dainxt** [comment]
Yikes, this was produced due to the 1.16.5 to 1.18 porting. Fixed in 1.0.6
