### ISSUE TITLE
Anchor Not Working  

### ISSUE THREAD

**Issue by Treehock** [dainxt/AncientClasses#15]
Version 1.18.2

Mod Version 1.0.6

No other mods loaded

The stone branches' ALT 5 does not anchor you

Still receive knockback from arrows
![2022-04-12_16 16 14](https://user-images.githubusercontent.com/65260754/163046644-9209b891-744f-4760-97aa-701f3db7e707.png)

and mobs
![2022-04-12_16 16 46](https://user-images.githubusercontent.com/65260754/163046642-13af0d34-7494-41be-9f4c-13075e33d551.png)

![2022-04-12_16 16 44](https://user-images.githubusercontent.com/65260754/163046647-5f29b3b9-593c-4f58-a435-e91e5bfc23de.png)

**Comment by dainxt** [comment]
Fixed in 1.0.10
