### ISSUE TITLE
Config Crash

### ISSUE THREAD

**Issue by Treehock** [dainxt/AncientClasses#17]
Version 1.18.2

Mod Version 1.0.10

No other mods loaded

After enabling custom values in the server config game crashes if you try to open/level up skills

**Comment by dainxt** [comment]
Can you post crash-logs?

**Comment by Scarasol** [comment]
I have the same question. And here is the log.
[crash-2022-11-23_21.06.37-client.txt](https://github.com/dainxt/AncientClasses/files/10075745/crash-2022-11-23_21.06.37-client.txt)

**Comment by dainxt** [comment]
Omw to fix, sorry for the late response

**Comment by dainxt** [comment]
Fixed on 1.0.14.
