### ISSUE TITLE
severe crash when ancient classes are used with cofh core

### ISSUE THREAD

**Issue by LILPRINCES** [dainxt/AncientClasses#18]
The game crashes directly when the player burns.

crash report:    https://pastebin.com/RyWLvbB4

servse log:    https://pastebin.com/rPa9xBbN

game verson:1.16.5
mod verson:AncientClasses-1.16.5-1.0.10

**Comment by LILPRINCES** [comment]
game verson:1.16.5
mod verson:AncientClasses-1.16.5-1.0.10

**Comment by dainxt** [comment]
Probably fixed as the issue #19 is directly related
