### ISSUE TITLE
Leafleafman third skill crash

### ISSUE THREAD

**Issue by LILPRINCES** [dainxt/AncientClasses#20]
Game crashes when using Leafman third ability on tall grass,by the way when using Leafman third skill on a cactus it doesn't have any effect.

no other mods loaded.

game verson:1.16.5
mod verson:AncientClasses-1.16.5-1.0.10

crash report: https://pastebin.com/4RSve5rX

servse log: https://pastebin.com/byMW4AxA

**Comment by dainxt** [comment]
Fixed in 1.0.12, cactus were wrongly included in the ability description.
