### ISSUE TITLE
[1.20.1] - Error on Launching Game

### ISSUE THREAD

**Issue by ToxinZangoose** [dainxt/AncientClasses#26]
Hello, 

I found a small bug that occurred when launching an instance with the latest Ancient Classes mod.

Here is the crash log.
https://mclo.gs/58TotUV

I love the tone and feel of this mod and would love to use it for 1.20.1, please let me know if there is anything else I can send to help.

Thank you for your time.

**Comment by dainxt** [comment]
Fixed in 2.0.3
