### ISSUE TITLE
Class diamond crash with Creeper explosion

### ISSUE THREAD

**Issue by HeinrichKrauser** [dainxt/AncientClasses#4]
Hello
I'd like to report an issue when the creeper explosion happen it constantly crash the game. In the crash report, it state that there is something happen with Diamond class looting behavior on the creeper. Hope you can fix it soo
[crash-2022-02-04_23.00.35-server.txt](https://github.com/dainxt/AncientClasses/files/8004504/crash-2022-02-04_23.00.35-server.txt)
n

**Comment by dainxt** [comment]
Fixed in 0.9.38
