### ISSUE TITLE
Feature Suggestion: Allow modpack makers to designate which items restore soul, reset your class, or can be used to channel

### ISSUE THREAD

**Issue by Not-February** [dainxt/AncientClasses#6]
I think it'd be nice if, for example, I could make chocolate glazed berries from Create restore soul like sweet berries do since they're *made* from sweet berries.

Customization in general would also be great for designating which items are "channeled" with per class, what immediately comes to mind is that since the Leaf Branch requires you to hold right click on a stick, other mods which might add right click functionality to sticks(such as placing them down for decoration with Supplementaries) suddenly became incredibly aggravating for that specific class. In this particular case Supplementaries' behavior can be disabled, but this may not always be the case for behavior with other mods and channeling items in general.

I'd suggest either functional config entries or with perhaps an item tag approach like I've seen some other mods like Tough as Nails do for their thirst restorative items, but being able to change things like this in any way would be wonderful.

**Comment by dainxt** [comment]
In 0.9.102 adding Staffs for every caster branch to use them. as well adding a configurable list adding BYG berries as a template to restore soul.
