### ISSUE TITLE
Interacting with any entity gives the "You cant learn this morph or already have" dialogue when using Leaf Branch

### ISSUE THREAD

**Issue by Not-February** [dainxt/AncientClasses#7]
This is confusing and a little bit annoying - I think the dialogue should only show up if you're interacting with an entity you can actually learn instead of literally any entity that you right-click. This message is popping up when I right click to trade with villagers or similar entities for example.

Forge 39.0.75
Ancient Classes 0.9.39

**Comment by dainxt** [comment]
Fixed so you have to sneak and interact with an entity for learning to morph. As well, added a configuration option to toggle this message off in 0.9.102
