### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Taknax** [dainxt/AncientClasses#8]
A skill book instead of ALT+C to manage the branches. It could be craftable and not accessable initialy (Also delete the hotkey, or hotkey can just be used if Skillbook is in the hand). Would feel more rewarding to craft the book and choice the branches after. And that would give the space to add some information about the branches and skills.
If you like my idea you could use this. 
![bone_book](https://user-images.githubusercontent.com/66703017/153792472-110d3d22-6e08-4ba4-a228-6f9ae0e3e004.png)
I enjoy your mod really and would like to see it grow.

**Comment by dainxt** [comment]
Added on 1.16.5-1.0 or will be added on 1.18.1-1.0. Need to install Patchouli to see the guide book.

**Comment by Taknax** [comment]
So cool. I am using the 1.16.5 version. I am gonna test it an tell you.
