### ISSUE TITLE
Conflict with my mod Charm and Nail

### ISSUE THREAD

**Issue by LaDestitute** [dainxt/AncientClasses#9]
Hello, a user has notified your mod has a conflict with my mod Charm and Nail.
Do you happen to to use global loot modifiers to add to chest loot tables? That's my hunch that you are since I don't have access to your source code as its not publicly available. They've reported if your mod is in with mine, your mod causes all chest loot tables to become empty.

My charm and nail mod:
https://gitlab.com/LaDestitute/charm-and-nail/-/tree/main/src/main/java/com/ladestitute/charmandnail

**Comment by dainxt** [comment]
No, I didn't use global loot modifiers for chest loots. Sorry for the late response, I've installed your mod (0.1) and mine (0.9.39) and chest loot tables at 1.18.1 are generating fine.  Let me know if you had any different result.

**Comment by LaDestitute** [comment]
Oh, I forgot to mention this is 1.16.5 and I only have both of our mods installed
![db42bd1701c3a149df5a45d278028b6c](https://user-images.githubusercontent.com/5476211/154782864-153839aa-1dc1-4e50-9d4e-88b4bad77e18.png)

**Comment by dainxt** [comment]
Tested with 0.9.102 on 1.16.5 with this mod and seems it is working fine, sorry for the late response again...
